# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Mr Ride' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mr Ride
  pod 'MMDrawerController', '~> 0.6'
  pod 'Charts', '~> 2.2.5'
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON', '~> 2.3'
  pod 'Google/Analytics'
  pod 'Amplitude-iOS', '~> 3.7.0'
end
